In [3]:
# 导入sklearn数据预处理模块
from sklearn import preprocessing
import numpy as np

In [4]:
# 3个样本3个特征
x = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1., -1.]])

In [5]:
x_scale = preprocessing.scale(x)
x_scale

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
# 按列求平均
x_scale.mean(axis=0)

array([0., 0., 0.])

In [9]:
# 按列求标准差
x_scale.std(axis=0)

array([1., 1., 1.])

In [ ]:
# True  False

In [ ]:
x = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1., -1.]])

In [10]:
# 实例化一个Binarizer()转化器，并训练参数
# 特征二值化默认阈值是0
binarizer = preprocessing.Binarizer().fit(x)
# 开始转化特征
binarizer.transform(x)

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [11]:
#当然也可以自己设置这个阀值，只需传出参数threshold即可
binarizer = preprocessing.Binarizer(threshold=1.5)
binarizer.transform(x)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [13]:
# 创建一个独热编码器
enc = preprocessing.OneHotEncoder()

# 随机模拟一些样本
sample = np.array([[0, 0, 3], 
                   [1, 1, 0], 
                   [0, 2, 1], 
                   [1, 0, 2]])
# fit来学习编码
enc.fit(sample)    

OneHotEncoder()

In [16]:
# 以下是独热编码器学习到的参数
enc.categories_

[array([0, 1]), array([0, 1, 2]), array([0, 1, 2, 3])]

In [17]:
# 进行编码
enc.transform([[0, 1, 3],
               [1, 2, 1]]).toarray()  

array([[1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 1., 0., 0.]])

In [20]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], 
        [-0.5, 6], 
        [0, 10], 
        [1, 18]]
# 实例化归一化转换器
scaler = MinMaxScaler()
# 学习参数
scaler.fit(data)

MinMaxScaler()

In [25]:
# 查看学习到的参数
print("样本每个特征的最大值：",scaler.data_max_)
print("样本每个特征的最小值：",scaler.data_min_)

样本每个特征的最大值： [ 1. 18.]
样本每个特征的最小值： [-1.  2.]


In [26]:
print(scaler.transform(data))

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


In [28]:
# 给一个新的样本做归一化转换
print(scaler.transform([[2, 2]]))

[[1.5 0. ]]


In [37]:
from sklearn.preprocessing import MaxAbsScaler
X = [[ 1., -1.,  -5.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
transformer = MaxAbsScaler().fit(X)
# 查看每个特征绝对值的最大值
print(transformer.max_abs_)

[2. 1. 5.]


In [38]:
transformer.transform(X)

array([[ 0.5, -1. , -1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.2]])

In [40]:
import pandas as pd 
sex = pd.Series(["male", "female", "female", "male"])

#获取一个LabelEncoder
le = preprocessing.LabelEncoder()

#训练LabelEncoder, 把male编码为1，female编码为0
le = le.fit(sex)
#使用训练好的LabelEncoder对原数据进行编码
sex = le.transform(sex)                
print(sex)

[1 0 0 1]


['setosa', 'versicolor', 'virginica', 'versicolor', 'setosa', 'virginica']

In [43]:
# 使用标签类别编码对鸢尾花类别做编码
target = ['setosa', 'versicolor', 'virginica', 
          'versicolor','setosa', 'virginica']
print(target)
le = preprocessing.LabelEncoder()
le = le.fit(target)
iris_target = le.transform(target) 
iris_target

array([0, 1, 2, 1, 0, 2])