In [1]:
import numpy as np

In [9]:
close = np.loadtxt('data.csv',delimiter=',',skiprows=1,usecols=6)

In [10]:
close

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [11]:
diff_close = np.diff(close)

In [12]:
diff_close

array([  3.22,   5.71,  -0.71,  -0.88,   3.06,   5.38,   3.32,   2.96,
        -3.62,   2.31,   2.33,   0.72,   3.23,  -4.83,  -7.74, -11.95,
         4.01,   0.26,   5.28,   5.05,  -3.9 ,   2.81,   7.44,   0.44,
        -4.64,   0.4 ,  -3.29,  -5.8 ,   5.32])

In [13]:
returns = diff_close/close[:-1]

In [14]:
returns

array([ 0.00958048,  0.01682777, -0.00205779, -0.00255576,  0.00890985,
        0.0155267 ,  0.00943503,  0.00833333, -0.01010721,  0.00651548,
        0.00652935,  0.00200457,  0.00897472, -0.01330102, -0.02160201,
       -0.03408832,  0.01184253,  0.00075886,  0.01539897,  0.01450483,
       -0.01104159,  0.00804443,  0.02112916,  0.00122372, -0.01288889,
        0.00112562, -0.00924781, -0.0164553 ,  0.01534601])

In [15]:
p_returns = returns.compress(returns>0)

In [16]:
p_returns

array([0.00958048, 0.01682777, 0.00890985, 0.0155267 , 0.00943503,
       0.00833333, 0.00651548, 0.00652935, 0.00200457, 0.00897472,
       0.01184253, 0.00075886, 0.01539897, 0.01450483, 0.00804443,
       0.02112916, 0.00122372, 0.00112562, 0.01534601])

In [17]:
p_index = np.where(returns>0)
p_index

(array([ 0,  1,  4,  5,  6,  7,  9, 10, 11, 12, 16, 17, 18, 19, 21, 22, 23,
        25, 28], dtype=int64),)

In [18]:
p2 = returns[p_index]

In [19]:
p2

array([0.00958048, 0.01682777, 0.00890985, 0.0155267 , 0.00943503,
       0.00833333, 0.00651548, 0.00652935, 0.00200457, 0.00897472,
       0.01184253, 0.00075886, 0.01539897, 0.01450483, 0.00804443,
       0.02112916, 0.00122372, 0.00112562, 0.01534601])

In [20]:
p3 = returns[returns>0]

In [21]:
p3

array([0.00958048, 0.01682777, 0.00890985, 0.0155267 , 0.00943503,
       0.00833333, 0.00651548, 0.00652935, 0.00200457, 0.00897472,
       0.01184253, 0.00075886, 0.01539897, 0.01450483, 0.00804443,
       0.02112916, 0.00122372, 0.00112562, 0.01534601])

In [23]:
log_returns = np.diff(np.log(close))
log_returns

array([ 0.00953488,  0.01668775, -0.00205991, -0.00255903,  0.00887039,
        0.01540739,  0.0093908 ,  0.0082988 , -0.01015864,  0.00649435,
        0.00650813,  0.00200256,  0.00893468, -0.01339027, -0.02183875,
       -0.03468287,  0.01177296,  0.00075857,  0.01528161,  0.01440064,
       -0.011103  ,  0.00801225,  0.02090904,  0.00122297, -0.01297267,
        0.00112499, -0.00929083, -0.01659219,  0.01522945])

In [24]:
volatility = np.std(log_returns)/np.mean(log_returns)
volatility

8.14354630702448

In [25]:
y_volatility = volatility/np.sqrt(1/252)
m_volatility = volatility/np.sqrt(1/12)

In [26]:
y_volatility

129.27478991115132

In [27]:
m_volatility

28.210071915112596

In [28]:
from datetime import datetime
import time

In [29]:
date1 = datetime.strptime('2021-07-31','%Y-%m-%d')
date1

datetime.datetime(2021, 7, 31, 0, 0)

In [30]:
date1.date()

datetime.date(2021, 7, 31)

In [35]:
date1.date().weekday()

5

In [34]:
date1.date().isoweekday()

6

In [36]:
sDate = np.loadtxt('data.csv',delimiter=',',skiprows=1,usecols=1,dtype=str)

In [37]:
sDate

array(['28-01-2011', '31-01-2011', '01-02-2011', '02-02-2011',
       '03-02-2011', '04-02-2011', '07-02-2011', '08-02-2011',
       '09-02-2011', '10-02-2011', '11-02-2011', '14-02-2011',
       '15-02-2011', '16-02-2011', '17-02-2011', '18-02-2011',
       '22-02-2011', '23-02-2011', '24-02-2011', '25-02-2011',
       '28-02-2011', '01-03-2011', '02-03-2011', '03-03-2011',
       '04-03-2011', '07-03-2011', '08-03-2011', '09-03-2011',
       '10-03-2011', '11-03-2011'], dtype='<U10')

In [38]:
def str2weekday(DataStr):
    return datetime.strptime(DataStr,'%d-%m-%Y').date().isoweekday()

In [39]:
listweekday = []

In [40]:
for item in sDate:
    listweekday.append(str2weekday(item))

In [ ]:
listweekday

In [42]:
weekday1 = np.array(listweekday)

In [43]:
weekday1

array([5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5])

In [50]:
monday = weekday1[weekday1==1]
monday

array([1, 1, 1, 1, 1])

In [51]:
weekday3,close3 = np.loadtxt('data.csv',delimiter=',',skiprows=1,usecols=(1,6),unpack=True,converters={1:str2weekday})

TypeError: strptime() argument 1 must be str, not bytes

In [60]:
def bytes2weekday(DataBytes):
    return datetime.strptime(DataBytes.decode('utf-8'),'%d-%m-%Y').date().isoweekday()

In [61]:
weekday4,close4 = np.loadtxt('data.csv',delimiter=',',skiprows=1,usecols=(1,6),unpack=True,converters={1:bytes2weekday})

In [62]:
weekday4

array([5., 1., 2., 3., 4., 5., 1., 2., 3., 4., 5., 1., 2., 3., 4., 5., 2.,
       3., 4., 5., 1., 2., 3., 4., 5., 1., 2., 3., 4., 5.])

In [63]:
close4

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [73]:
avgs = np.zeros(5)
avgs

array([0., 0., 0., 0., 0.])

In [74]:
for i in range(1,6):
    # 遍历周一到周五
    w_index = np.where(weekday4 == i)
    # 找到周一到周五每天对应的索引
    print('周%d对应的索引是：'%i,w_index)
#     w_close = Close4[w_index]
    # 获取周一到周五对应的收盘价，用条件索引
    w_close = np.take(close4,w_index)
    # take是从数组中按照索引提取值，返回新的数组
    print('周%d对应的收盘价是：'%i,w_close)
    avg = np.mean(w_close)
    # 针对周几的收盘价计算均值
    print('周%d对应的收盘价均价是：'%i,avg)
    avgs[i-1] = avg
    # 将计算出的周一到周五的收盘价均价写入avgs数组

周1对应的索引是： (array([ 1,  6, 11, 20, 25], dtype=int64),)
周1对应的收盘价是： [[339.32 351.88 359.18 353.21 355.36]]
周1对应的收盘价均价是： 351.7900000000001
周2对应的索引是： (array([ 2,  7, 12, 16, 21, 26], dtype=int64),)
周2对应的收盘价是： [[345.03 355.2  359.9  338.61 349.31 355.76]]
周2对应的收盘价均价是： 350.63500000000005
周3对应的索引是： (array([ 3,  8, 13, 17, 22, 27], dtype=int64),)
周3对应的收盘价是： [[344.32 358.16 363.13 342.62 352.12 352.47]]
周3对应的收盘价均价是： 352.1366666666666
周4对应的索引是： (array([ 4,  9, 14, 18, 23, 28], dtype=int64),)
周4对应的收盘价是： [[343.44 354.54 358.3  342.88 359.56 346.67]]
周4对应的收盘价均价是： 350.8983333333333
周5对应的索引是： (array([ 0,  5, 10, 15, 19, 24, 29], dtype=int64),)
周5对应的收盘价是： [[336.1  346.5  356.85 350.56 348.16 360.   351.99]]
周5对应的收盘价均价是： 350.0228571428571
